baseURL = "https://imaginedemainlemonde.netlify.app"
languageCode = "fr-be"
title = "Imagine, Demain le monde | Slow press magazine"
Paginate = 6

[markup]

[markup.goldmark]

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "categories"

[[menu.main]]
name = "N° en cours"
url = "/numero-en-cours/"
weight = 1

[[menu.main]]
name = "Contenus"
url = "/nos-contenus/"
weight = 2

[[menu.main]]
name = "Le projet Imagine"
url = "/imagine-2020/"
weight = 3

[[menu.main]]
name = "Archives"
url = "https://archives.imagine-magazine.com/lire/?page=archive"
weight = 4