---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/categories
  label: Catégories
  create: all
  match: "**/*"
  templates:
  - categorie
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/numeros
  label: Numeros
  create: documents
  match: "**/*"
  templates:
  - numero-en-cours
- type: directory
  path: content/libre-acces
  label: Nos contenus
  create: documents
  match: "**/*"
  templates:
  - article
  - titre-de-categorie
- type: document
  path: data/infos.toml
  label: Informations générales
- type: document
  path: data/cta.toml
  label: Call to action
- type: document
  path: data/colors.yaml
  label: Couleurs
upload_dir: ''
public_path: https://res.cloudinary.com/drg3m95yg/image/upload/c_limit,dpr_auto,q_70,w_1000,f_auto
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.69.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.69.2
